[project]
name = "xray-logs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.2",
    "sqlalchemy>=2.0.34",
    "asyncpg>=0.30.0",
    "pydantic-settings>=2.4.0",
    "uvicorn>=0.38.0",
]
