[project]
name = "xray-logs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.2",
    "psycopg>=3.2.12",
    "uvicorn>=0.38.0",
    "sqlalchemy[asyncio]>=2.0.35",
    "pydantic-settings>=2.5.2",
    "asyncpg>=0.30.0",
]
